cabal-version:      3.0
name:               Hsue
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Qerfcxz
-- maintainer:
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Engine.Atlas
        Engine.Collector
        Engine.Container
        Engine.Coroutine
        Engine.Engine
        Engine.Helper
        Engine.Leaf
        Engine.Node
        Engine.Projection
        Engine.Request
        Engine.Shader
        Engine.Text
        Engine.Type
        Engine.Window
        MSDF.Function
        MSDF.Type
        SDL.Function
        SDL.Include
        SDL.Type
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.18.3.0,
        bytestring ==0.12.2.0,
        containers ==0.8,
        text ==2.1.4,
        vector ==0.13.2.0
    hs-source-dirs:   src
    default-language: Haskell2010

executable Hsue
    import:           warnings
    main-is:          Main.hs
    ghc-options:
        -threaded
        -with-rtsopts=-N
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.18.3.0,
        bytestring ==0.12.2.0,
        containers ==0.8,
        text ==2.1.4,
        vector ==0.13.2.0,
        Hsue
    extra-libraries:
        msdf
        msdf-atlas-gen
        msdfgen-ext
        msdfgen-core
        SDL3
        SDL3_image
    include-dirs:
        C:\D\MSYS2\mingw64\include\SDL3
        C:\D\MSYS2\mingw64\include\SDL3_image
    extra-lib-dirs:
        C:\D\MSYS2\mingw64\lib
        C:\D\msdf-atlas-gen-master\build
        C:\D\msdf-atlas-gen-master\build\msdfgen
    hs-source-dirs:   app
    default-language: Haskell2010