{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE NamedFieldPuns #-}

module Engine.Coroutine where

import Engine.Type
import qualified Data.IntMap as DIM
import qualified Data.IntSet as DIS
import qualified Data.Sequence as DS

from_coroutine::Coroutine a->(DIM.IntMap (Linear_coroutine a),Int,Int)
from_coroutine coroutine=let (linear_coroutine,coroutine_number,int_index,code_index)=from_coroutine_a coroutine 1 0 0 1 DIM.empty in (DIM.insert code_index Linear_end linear_coroutine,coroutine_number,int_index)

from_coroutine_a::Coroutine a->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int,Int)
from_coroutine_a this_coroutine clone_number code_index int_index coroutine_number linear_coroutine=case this_coroutine of
    Done->(linear_coroutine,coroutine_number,int_index,code_index)
    Emit {emit}->(DIM.insert code_index (Linear_emit {emit=emit}) linear_coroutine,coroutine_number,int_index,code_index+1)
    Wait {dynamic_int}->(DIM.insert (code_index+1) (Linear_wait {int_index=int_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) linear_coroutine),coroutine_number,int_index+clone_number,code_index+2)
    Forever {coroutine}->let (new_linear_coroutine,new_coroutine_number,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index int_index coroutine_number linear_coroutine in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) new_linear_coroutine,new_coroutine_number,new_int_index,new_code_index+1)
    Fork {multiple_coroutine}->case multiple_coroutine of
        DS.Empty->(linear_coroutine,coroutine_number,int_index,code_index)
        coroutine DS.:<| other_coroutine->let new_code_index=code_index+1 in let int=DS.length other_coroutine in let (new_linear_coroutine,new_coroutine_number,new_int_index,new_new_code_index)=from_coroutine_a coroutine clone_number (new_code_index+int) (int_index+2*clone_number) (coroutine_number+int*clone_number) linear_coroutine in let new_new_int_index=int_index+clone_number in let (final_linear_coroutine,final_coroutine_number,final_int_index,final_code_index)=fork_coroutine other_coroutine DIS.empty new_code_index clone_number (new_new_code_index+1) new_int_index new_coroutine_number (DIM.insert code_index (Linear_register {first_int_index=int_index,second_int_index=new_new_int_index,int=int}) new_linear_coroutine) in (DIM.insert final_code_index (Linear_deregister {first_int_index=int_index,second_int_index=new_new_int_index,clone_number=clone_number}) final_linear_coroutine,final_coroutine_number,final_int_index,final_code_index+1)
    While {dynamic_bool,coroutine}->let (new_linear_coroutine,new_coroutine_number,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number (code_index+1) int_index coroutine_number linear_coroutine in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) (DIM.insert code_index (Linear_false_jump {code_index=new_code_index+1,dynamic_bool=dynamic_bool}) new_linear_coroutine),new_coroutine_number,new_int_index,new_code_index+1)
    Repeat {dynamic_int,coroutine}->let new_code_index=code_index+2 in let (new_linear_coroutine,new_coroutine_number,new_int_index,new_new_code_index)=from_coroutine_a coroutine clone_number new_code_index (int_index+clone_number) coroutine_number linear_coroutine in let new_new_new_code_index=new_new_code_index+1 in (DIM.insert new_new_code_index (Linear_one_more_jump {int_index=int_index,code_index=new_code_index}) (DIM.insert (code_index+1) (Linear_one_less_jump {int_index=int_index,code_index=new_new_new_code_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) new_linear_coroutine)),new_coroutine_number,new_int_index,new_new_new_code_index)
    Clone {int,coroutine}->let new_int=int-1 in if new_int<0 then (linear_coroutine,coroutine_number,int_index,code_index) else let (new_linear_coroutine,new_coroutine_number,new_int_index,new_code_index)=from_coroutine_a coroutine (int*clone_number) (code_index+1) (int_index+2*clone_number) (coroutine_number+new_int*clone_number) linear_coroutine in let new_new_int_index=int_index+clone_number in (DIM.insert new_code_index (Linear_deregister {first_int_index=int_index,second_int_index=new_new_int_index,clone_number=clone_number}) (DIM.insert code_index (Linear_clone {first_int_index=int_index,second_int_index=new_new_int_index,clone_number=clone_number,int=new_int}) new_linear_coroutine),new_coroutine_number,new_int_index,new_code_index+1)
    Then {first_coroutine,second_coroutine}->let (first_linear_coroutine,first_coroutine_number,first_int_index,first_code_index)=from_coroutine_a first_coroutine clone_number code_index int_index coroutine_number linear_coroutine in let (second_linear_coroutine,second_coroutine_number,second_int_index,second_code_index)=from_coroutine_a second_coroutine clone_number first_code_index int_index coroutine_number first_linear_coroutine in (second_linear_coroutine,max first_coroutine_number second_coroutine_number,max first_int_index second_int_index,second_code_index)
    If {dynamic_bool,first_coroutine,second_coroutine}->let (first_linear_coroutine,first_coroutine_number,first_int_index,first_code_index)=from_coroutine_a first_coroutine clone_number (code_index+1) int_index coroutine_number linear_coroutine in let new_code_index=first_code_index+1 in let (second_linear_coroutine,second_coroutine_number,second_int_index,second_code_index)=from_coroutine_a second_coroutine clone_number new_code_index int_index coroutine_number first_linear_coroutine in (DIM.insert first_code_index (Linear_jump {code_index=second_code_index}) (DIM.insert code_index (Linear_false_jump {code_index=new_code_index,dynamic_bool=dynamic_bool}) second_linear_coroutine),max first_coroutine_number second_coroutine_number,max first_int_index second_int_index,second_code_index)

fork_coroutine::DS.Seq (Coroutine a)->DIS.IntSet->Int->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int,Int)
fork_coroutine multiple_coroutine jump_code_index fork_code_index clone_number code_index int_index coroutine_number linear_coroutine=case multiple_coroutine of
    DS.Empty->let new_code_index=code_index-1 in (DIS.foldl' (\this_linear_coroutine this_code_index->DIM.insert this_code_index (Linear_jump {code_index=new_code_index}) this_linear_coroutine) linear_coroutine jump_code_index,coroutine_number,int_index,new_code_index)
    coroutine DS.:<| other_coroutine->let (new_linear_coroutine,new_coroutine_number,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index int_index coroutine_number linear_coroutine in fork_coroutine other_coroutine (DIS.insert (code_index-1) jump_code_index) (fork_code_index+1) clone_number (new_code_index+1) new_int_index new_coroutine_number (DIM.insert fork_code_index (Linear_fork {code_index=code_index,clone_number=clone_number}) new_linear_coroutine)