{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedRecordDot #-}

module Engine.Coroutine where

import Engine.Container
import Engine.Type
import qualified Data.Foldable as DF
import qualified Data.IntMap as DIM
import qualified Data.IntSet as DIS
import qualified Data.Sequence as DS

init_coroutine_state::Widget a->Coroutine_state a
init_coroutine_state widget=Coroutine_state {widget=widget,variable=DIM.empty,program_counter=DIM.singleton 0 (Program_counter {code_index=0,clone_index=0}),index_group=DIM.empty,main_index_group=DS.singleton 0,index_group_index=0,program_counter_index=1}

to_coroutine::Raw_coroutine a ()->Coroutine a
to_coroutine raw_coroutine=let coroutine_sequence=raw_coroutine.coroutine_sequence in case coroutine_sequence of
    DS.Empty->Done
    coroutine DS.:<| other_coroutine->if DS.null other_coroutine then coroutine else Then {coroutine_sequence=coroutine_sequence}

lift_coroutine::Coroutine a->Raw_coroutine a ()
lift_coroutine coroutine=Raw_coroutine {coroutine_sequence=DS.singleton coroutine,value=()}

do_empty::Raw_coroutine a ()
do_empty=Raw_coroutine {coroutine_sequence=DS.empty,value=()}

do_emit::(Engine a->Widget a->(Widget a,Engine a))->Raw_coroutine a ()
do_emit emit=lift_coroutine (Emit {emit=emit})

do_wait::Dynamic_int a->Raw_coroutine a ()
do_wait dynamic_int=lift_coroutine (Wait {dynamic_int=dynamic_int})

do_forever::Raw_coroutine a ()->Raw_coroutine a ()
do_forever raw_coroutine=lift_coroutine (Forever {coroutine=to_coroutine raw_coroutine})

do_then::Raw_coroutine a ()->Raw_coroutine a ()
do_then raw_coroutine=let coroutine_sequence=raw_coroutine.coroutine_sequence in case coroutine_sequence of
    DS.Empty->do_empty
    coroutine DS.:<| other_coroutine->if DS.null other_coroutine then lift_coroutine coroutine else lift_coroutine (Then {coroutine_sequence=coroutine_sequence})

do_while::Dynamic_bool a->Raw_coroutine a ()->Raw_coroutine a ()
do_while dynamic_bool raw_coroutine=lift_coroutine (While {dynamic_bool=dynamic_bool,coroutine=to_coroutine raw_coroutine})

do_pause::Dynamic_bool a->Raw_coroutine a ()->Raw_coroutine a ()
do_pause dynamic_bool raw_coroutine=lift_coroutine (Pause {dynamic_bool=dynamic_bool,coroutine=to_coroutine raw_coroutine})

do_skip::Dynamic_bool a->Raw_coroutine a ()->Raw_coroutine a ()
do_skip dynamic_bool raw_coroutine=lift_coroutine (Skip {dynamic_bool=dynamic_bool,coroutine=to_coroutine raw_coroutine})

do_repeat::Dynamic_int a->Raw_coroutine a ()->Raw_coroutine a ()
do_repeat dynamic_int raw_coroutine=lift_coroutine (Repeat {dynamic_int=dynamic_int,coroutine=to_coroutine raw_coroutine})

do_clone::Int->Raw_coroutine a ()->Raw_coroutine a ()
do_clone int raw_coroutine=lift_coroutine (Clone {int=int,coroutine=to_coroutine raw_coroutine})

do_if::Dynamic_bool a->Raw_coroutine a ()->Raw_coroutine a ()->Raw_coroutine a ()
do_if dynamic_bool first_raw_coroutine second_raw_coroutine=lift_coroutine (If {dynamic_bool=dynamic_bool,first_coroutine=to_coroutine first_raw_coroutine,second_coroutine=to_coroutine second_raw_coroutine})

do_dynamic_clone::Dynamic_int a->Int->Raw_coroutine a ()->Raw_coroutine a ()
do_dynamic_clone dynamic_int int raw_coroutine=lift_coroutine (Dynamic_clone {dynamic_int=dynamic_int,int=int,coroutine=to_coroutine raw_coroutine})

do_case::Dynamic_int a->Raw_coroutine a ()->Raw_coroutine a ()
do_case dynamic_int raw_coroutine=let coroutine_sequence=raw_coroutine.coroutine_sequence in case coroutine_sequence of
    DS.Empty->do_empty
    coroutine DS.:<| other_coroutine->let int=DS.length other_coroutine in if int==0 then lift_coroutine coroutine else lift_coroutine (Case {dynamic_int=dynamic_int,int=int+1,coroutine_sequence=coroutine_sequence})

do_fork::Raw_coroutine a ()->Raw_coroutine a ()
do_fork raw_coroutine=let coroutine_sequence=raw_coroutine.coroutine_sequence in case coroutine_sequence of
    DS.Empty->do_empty
    coroutine DS.:<| other_coroutine->let int=DS.length other_coroutine in if int==0 then lift_coroutine coroutine else lift_coroutine (Fork {int=int,coroutine=coroutine,coroutine_sequence=other_coroutine})

do_race::Dynamic_int a->Int->Raw_coroutine a ()->Raw_coroutine a ()
do_race dynamic_int int raw_coroutine=let coroutine_sequence=raw_coroutine.coroutine_sequence in case coroutine_sequence of
    DS.Empty->do_empty
    coroutine DS.:<| other_coroutine->let new_int=DS.length other_coroutine in if new_int==0 then lift_coroutine coroutine else lift_coroutine (Race {dynamic_int=dynamic_int,first_int=int,second_int=new_int+1,coroutine_sequence=coroutine_sequence})

from_coroutine::Coroutine a->(DIM.IntMap (Linear_coroutine a),Int)
from_coroutine coroutine=let (linear_coroutine,int_index,code_index)=from_coroutine_a coroutine 1 0 0 DIM.empty in (DIM.insert code_index Linear_end linear_coroutine,int_index)

from_coroutine_a::Coroutine a->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int)
from_coroutine_a this_coroutine clone_number code_index int_index linear_coroutine=case this_coroutine of
    Done->(linear_coroutine,int_index,code_index)
    Emit {emit}->(DIM.insert code_index (Linear_emit {emit=emit}) linear_coroutine,int_index,code_index+1)
    Wait {dynamic_int}->(DIM.insert (code_index+1) (Linear_wait {int_index=int_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) linear_coroutine),int_index+clone_number,code_index+2)
    Forever {coroutine}->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index int_index linear_coroutine in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) new_linear_coroutine,new_int_index,new_code_index+1)
    Then {coroutine_sequence}->DF.foldl' (\(this_linear_coroutine,this_int_index,this_code_index) coroutine->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number this_code_index int_index this_linear_coroutine in (new_linear_coroutine,max this_int_index new_int_index,new_code_index)) (linear_coroutine,int_index,code_index) coroutine_sequence
    While {dynamic_bool,coroutine}->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number (code_index+1) int_index linear_coroutine in let end_code_index=new_code_index+1 in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) (DIM.insert code_index (Linear_false_jump {code_index=end_code_index,dynamic_bool=dynamic_bool}) new_linear_coroutine),new_int_index,end_code_index)
    Pause {dynamic_bool,coroutine}->let body_code_index=code_index+3 in let countdown_int_index=int_index+clone_number in let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number body_code_index (int_index+2*clone_number) linear_coroutine in let loop_code_index=new_code_index+2 in let yield_code_index=loop_code_index+3 in let jump_code_index=loop_code_index+5 in (DIM.insert jump_code_index (Linear_kill_group {int_index=int_index,int=1}) (DIM.insert (loop_code_index+4) (Linear_jump {code_index=loop_code_index}) (DIM.insert yield_code_index Linear_yield (DIM.insert (loop_code_index+2) (Linear_wake {int_index=int_index}) (DIM.insert (loop_code_index+1) (Linear_true_jump {code_index=yield_code_index,dynamic_bool=dynamic_bool}) (DIM.insert loop_code_index (Linear_less_jump {int_index=countdown_int_index,code_index=jump_code_index,int=1}) (DIM.insert (new_code_index+1) Linear_end (DIM.insert new_code_index (Linear_countdown {int_index=countdown_int_index}) (DIM.insert (code_index+2) (Linear_jump {code_index=loop_code_index}) (DIM.insert (code_index+1) (Linear_create_group {int_index=int_index,group_code_index=DIM.singleton 0 body_code_index,int=1}) (DIM.insert code_index (Linear_int {int_index=countdown_int_index,int=1}) new_linear_coroutine)))))))))),new_int_index,loop_code_index+6)
    Skip {dynamic_bool,coroutine}->let body_code_index=code_index+3 in let countdown_int_index=int_index+clone_number in let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number body_code_index (int_index+2*clone_number) linear_coroutine in let loop_code_index=new_code_index+2 in let jump_code_index=loop_code_index+5 in (DIM.insert jump_code_index (Linear_kill_group {int_index=int_index,int=1}) (DIM.insert (loop_code_index+4) (Linear_jump {code_index=loop_code_index}) (DIM.insert (loop_code_index+3) Linear_yield (DIM.insert (loop_code_index+2) (Linear_wake {int_index=int_index}) (DIM.insert (loop_code_index+1) (Linear_true_jump {code_index=jump_code_index,dynamic_bool=dynamic_bool}) (DIM.insert loop_code_index (Linear_less_jump {int_index=countdown_int_index,code_index=jump_code_index,int=1}) (DIM.insert (new_code_index+1) Linear_end (DIM.insert new_code_index (Linear_countdown {int_index=countdown_int_index}) (DIM.insert (code_index+2) (Linear_jump {code_index=loop_code_index}) (DIM.insert (code_index+1) (Linear_create_group {int_index=int_index,group_code_index=DIM.singleton 0 body_code_index,int=1}) (DIM.insert code_index (Linear_int {int_index=countdown_int_index,int=1}) new_linear_coroutine)))))))))),new_int_index,loop_code_index+6)
    Repeat {dynamic_int,coroutine}->let loop_code_index=code_index+2 in let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number loop_code_index (int_index+clone_number) linear_coroutine in let end_code_index=new_code_index+1 in (DIM.insert new_code_index (Linear_one_more_jump {int_index=int_index,code_index=loop_code_index}) (DIM.insert (code_index+1) (Linear_one_less_jump {int_index=int_index,code_index=end_code_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) new_linear_coroutine)),new_int_index,end_code_index)
    Clone {int,coroutine}->let new_int=int-1 in if new_int<0 then (linear_coroutine,int_index,code_index) else let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine (int*clone_number) (code_index+1) (int_index+clone_number) linear_coroutine in (DIM.insert new_code_index (Linear_clone_kill {int_index=int_index,clone_number=clone_number}) (DIM.insert code_index (Linear_clone {int_index=int_index,clone_number=clone_number,int=new_int}) new_linear_coroutine),new_int_index,new_code_index+1)
    If {dynamic_bool,first_coroutine,second_coroutine}->let (first_linear_coroutine,first_int_index,first_code_index)=from_coroutine_a first_coroutine clone_number (code_index+1) int_index linear_coroutine in let new_code_index=first_code_index+1 in let (second_linear_coroutine,second_int_index,second_code_index)=from_coroutine_a second_coroutine clone_number new_code_index int_index first_linear_coroutine in (DIM.insert first_code_index (Linear_jump {code_index=second_code_index}) (DIM.insert code_index (Linear_false_jump {code_index=new_code_index,dynamic_bool=dynamic_bool}) second_linear_coroutine),max first_int_index second_int_index,second_code_index)
    Dynamic_clone {dynamic_int,int,coroutine}->let new_int=int-1 in if new_int<0 then (linear_coroutine,int_index,code_index) else let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine (int*clone_number) (code_index+1) (int_index+clone_number) linear_coroutine in let kill_code_index=new_code_index+1 in (DIM.insert new_code_index (Linear_clone_kill {int_index=int_index,clone_number=clone_number}) (DIM.insert code_index (Linear_dynamic_clone {int_index=int_index,code_index=kill_code_index,clone_number=clone_number,dynamic_int=dynamic_int,int=new_int}) new_linear_coroutine),new_int_index,kill_code_index)
    Case {dynamic_int,int,coroutine_sequence}->let (new_linear_coroutine,new_int_index,new_code_index,single_linear_coroutine)=case_coroutine DIM.empty DIS.empty coroutine_sequence int 0 (int_index+clone_number) clone_number (code_index+2) int_index linear_coroutine in (DIM.insert (code_index+1) single_linear_coroutine (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) new_linear_coroutine),new_int_index,new_code_index)
    Fork {int,coroutine,coroutine_sequence}->let body_code_index=code_index+1 in let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number (body_code_index+int) (int_index+clone_number) linear_coroutine in let (final_linear_coroutine,final_int_index,final_code_index)=fork_coroutine DIS.empty coroutine_sequence body_code_index clone_number (new_code_index+1) new_int_index (DIM.insert code_index (Linear_int {int_index=int_index,int=int}) new_linear_coroutine) in (DIM.insert final_code_index (Linear_fork_kill {int_index=int_index}) final_linear_coroutine,final_int_index,final_code_index+1)
    Race {dynamic_int,first_int,second_int,coroutine_sequence}->let countdown_int_index=int_index+clone_number in let (new_linear_coroutine,new_int_index,new_code_index,group_code_index)=race_coroutine coroutine_sequence 0 countdown_int_index clone_number (code_index+3) (int_index+2*clone_number) linear_coroutine in let kill_code_index=new_code_index+4 in (DIM.insert kill_code_index (Linear_kill_group {int_index=int_index,int=second_int}) (DIM.insert (new_code_index+3) (Linear_jump {code_index=new_code_index}) (DIM.insert (new_code_index+2) Linear_yield (DIM.insert (new_code_index+1) (Linear_wake_group {int_index=int_index,dynamic_int=dynamic_int,int=second_int}) (DIM.insert new_code_index (Linear_less_jump {int_index=countdown_int_index,code_index=kill_code_index,int=second_int-first_int+1}) (DIM.insert (code_index+2) (Linear_jump {code_index=new_code_index}) (DIM.insert (code_index+1) (Linear_create_group {int_index=int_index,group_code_index=group_code_index,int=second_int}) (DIM.insert code_index (Linear_int {int_index=countdown_int_index,int=second_int}) new_linear_coroutine))))))),new_int_index,new_code_index+5)

case_coroutine::DIM.IntMap Int->DIS.IntSet->DS.Seq (Coroutine a)->Int->Int->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int,Linear_coroutine a)
case_coroutine case_code_index jump_code_index coroutine_sequence int index max_int_index clone_number code_index int_index linear_coroutine=case coroutine_sequence of
    DS.Empty->let (new_linear_coroutine,new_code_index)=case_coroutine_a case_code_index int 0 code_index int_index linear_coroutine in (DIS.foldl' (\this_linear_coroutine this_code_index->DIM.insert this_code_index (Linear_jump {code_index=new_code_index}) this_linear_coroutine) new_linear_coroutine jump_code_index,max_int_index,new_code_index,Linear_jump {code_index=code_index})
    coroutine DS.:<| other_coroutine->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index (int_index+clone_number) linear_coroutine in case_coroutine (DIM.insert index code_index case_code_index) (DIS.insert new_code_index jump_code_index) other_coroutine int (index+1) (max new_int_index max_int_index) clone_number (new_code_index+1) int_index new_linear_coroutine

case_coroutine_a::DIM.IntMap Int->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int)
case_coroutine_a case_code_index int index code_index int_index linear_coroutine=case int of
    1->(DIM.insert code_index (Linear_jump {code_index=intmap_lookup index case_code_index}) linear_coroutine,code_index+1)
    _->let half_int=div int 2 in let new_int=index+half_int in let (right_linear_coroutine,right_code_index)=case_coroutine_a case_code_index (int-half_int) new_int (code_index+1) int_index linear_coroutine in let (left_linear_coroutine,left_code_index)=case_coroutine_a case_code_index half_int index right_code_index int_index right_linear_coroutine in (DIM.insert code_index (Linear_less_jump {int_index=int_index,code_index=right_code_index,int=new_int}) left_linear_coroutine,left_code_index)

fork_coroutine::DIS.IntSet->DS.Seq (Coroutine a)->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int)
fork_coroutine jump_code_index coroutine_sequence fork_code_index clone_number code_index int_index linear_coroutine=case coroutine_sequence of
    DS.Empty->let new_code_index=code_index-1 in (DIS.foldl' (\this_linear_coroutine this_code_index->DIM.insert this_code_index (Linear_jump {code_index=new_code_index}) this_linear_coroutine) linear_coroutine jump_code_index,int_index,new_code_index)
    coroutine DS.:<| other_coroutine->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index int_index linear_coroutine in fork_coroutine (DIS.insert (code_index-1) jump_code_index) other_coroutine (fork_code_index+1) clone_number (new_code_index+1) new_int_index (DIM.insert fork_code_index (Linear_fork {code_index=code_index}) new_linear_coroutine)

race_coroutine::DS.Seq (Coroutine a)->Int->Int->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int,DIM.IntMap Int)
race_coroutine coroutine_sequence index countdown_int_index clone_number code_index int_index linear_coroutine=case coroutine_sequence of
    DS.Empty->(linear_coroutine,int_index,code_index,DIM.empty)
    coroutine DS.:<| other_coroutine->let (new_linear_coroutine,new_int_index,new_code_index)=from_coroutine_a coroutine clone_number code_index int_index linear_coroutine in let (final_linear_coroutine,final_int_index,final_code_index,group_code_index)=race_coroutine other_coroutine (index+1) countdown_int_index clone_number (new_code_index+2) (max int_index new_int_index) (DIM.insert (new_code_index+1) Linear_end (DIM.insert new_code_index (Linear_countdown {int_index=countdown_int_index}) new_linear_coroutine)) in (final_linear_coroutine,final_int_index,final_code_index,DIM.insert index code_index group_code_index)

run_coroutine::DIM.IntMap (Linear_coroutine a)->Int->Int->DS.Seq Int->DS.Seq Int->DS.Seq Int->DIM.IntMap (DS.Seq Int)->DIM.IntMap Program_counter->DIM.IntMap Int->Engine a->Widget a->(Widget a,Engine a,DIM.IntMap Int,DIM.IntMap Program_counter,DIM.IntMap (DS.Seq Int),DS.Seq Int,Int,Int)
run_coroutine linear_coroutine program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget=case newborn_main_index_group of
    DS.Empty->case main_index_group of
        DS.Empty->(widget,engine,variable,program_counter,index_group,survived_main_index_group,index_group_index,program_counter_index)
        (main_index DS.:<| other_main_index)->let (new_program_counter,single_program_counter)=intmap_delete_lookup main_index program_counter in run_coroutine_a linear_coroutine main_index single_program_counter.clone_index single_program_counter.code_index program_counter_index index_group_index survived_main_index_group DS.empty other_main_index index_group new_program_counter variable engine widget
    (main_index DS.:<| other_main_index)->let (new_program_counter,single_program_counter)=intmap_delete_lookup main_index program_counter in run_coroutine_a linear_coroutine main_index single_program_counter.clone_index single_program_counter.code_index program_counter_index index_group_index survived_main_index_group DS.empty (other_main_index DS.>< main_index_group) index_group new_program_counter variable engine widget

run_coroutine_a::DIM.IntMap (Linear_coroutine a)->Int->Int->Int->Int->Int->DS.Seq Int->DS.Seq Int->DS.Seq Int->DIM.IntMap (DS.Seq Int)->DIM.IntMap Program_counter->DIM.IntMap Int->Engine a->Widget a->(Widget a,Engine a,DIM.IntMap Int,DIM.IntMap Program_counter,DIM.IntMap (DS.Seq Int),DS.Seq Int,Int,Int)
run_coroutine_a linear_coroutine main_index clone_index this_code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget=case intmap_lookup this_code_index linear_coroutine of
    Linear_end->run_coroutine linear_coroutine program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_yield->run_coroutine linear_coroutine program_counter_index index_group_index (survived_main_index_group DS.|> main_index) newborn_main_index_group main_index_group index_group (intmap_insert main_index (Program_counter {code_index=this_code_index+1,clone_index=clone_index}) program_counter) variable engine widget
    Linear_emit {emit}->let (new_widget,new_engine)=emit engine widget in run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable new_engine new_widget
    Linear_wait {int_index}->let (new_variable,int)=intmap_update_lookup (int_index+clone_index) (\this_int->this_int-1) variable in if 0<int then run_coroutine linear_coroutine program_counter_index index_group_index (survived_main_index_group DS.|> main_index) newborn_main_index_group main_index_group index_group (intmap_insert main_index (Program_counter {code_index=this_code_index,clone_index=clone_index}) program_counter) new_variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget
    Linear_countdown {int_index}->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter (intmap_update (int_index+clone_index) (\int->int-1) variable) engine widget
    Linear_fork_kill {int_index}->let (new_variable,int)=intmap_update_lookup (int_index+clone_index) (\this_int->this_int-1) variable in if 0<int then run_coroutine linear_coroutine program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget
    Linear_wake {int_index}->let new_index_group_index=intmap_lookup (int_index+clone_index) variable in let (new_index_group_map,maybe_single_index_group)=intmap_delete_maybe_lookup new_index_group_index index_group in case maybe_single_index_group of
        Nothing->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
        Just single_index_group->let (new_widget,new_engine,new_variable,new_program_counter,new_index_group,new_survived_main_index_group,new_new_index_group_index,new_program_counter_index)=run_coroutine linear_coroutine program_counter_index index_group_index DS.empty DS.empty single_index_group new_index_group_map program_counter variable engine widget in run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) new_program_counter_index new_new_index_group_index survived_main_index_group newborn_main_index_group main_index_group (if DS.null new_survived_main_index_group then new_index_group else DIM.insert new_index_group_index new_survived_main_index_group new_index_group) new_program_counter new_variable new_engine new_widget
    Linear_fork {code_index}->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) (program_counter_index+1) index_group_index survived_main_index_group (newborn_main_index_group DS.|> program_counter_index) main_index_group index_group (intmap_insert program_counter_index (Program_counter {code_index=code_index,clone_index=clone_index}) program_counter) variable engine widget
    Linear_jump {code_index}->run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_one_less_jump {int_index,code_index}->if intmap_lookup (int_index+clone_index) variable<1 then run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_one_more_jump {int_index,code_index}->let (new_variable,int)=intmap_update_lookup (int_index+clone_index) (\this_int->this_int-1) variable in if 1<int then run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget
    Linear_clone_kill {int_index,clone_number}->let new_clone_index=mod clone_index clone_number in let (new_variable,int)=intmap_update_lookup (int_index+new_clone_index) (\this_int->this_int-1) variable in if 0<int then run_coroutine linear_coroutine program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget else run_coroutine_a linear_coroutine main_index new_clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter new_variable engine widget
    Linear_dynamic_int {int_index,dynamic_int}->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter (DIM.insert (int_index+clone_index) (dynamic_int.dynamic_int engine widget) variable) engine widget
    Linear_int {int_index,int}->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter (DIM.insert (int_index+clone_index) int variable) engine widget
    Linear_kill_group {int_index,int}->let (new_program_counter,new_index_group)=run_kill_group int 0 (intmap_lookup (int_index+clone_index) variable) index_group program_counter in run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group new_index_group new_program_counter variable engine widget
    Linear_true_jump {code_index,dynamic_bool}->if dynamic_bool.dynamic_bool engine widget then run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_false_jump {code_index,dynamic_bool}->if dynamic_bool.dynamic_bool engine widget then run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget else run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_less_jump {int_index,code_index,int}->if intmap_lookup (int_index+clone_index) variable<int then run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget else run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
    Linear_create_group {int_index,group_code_index,int}->let (new_program_counter,new_index_group,new_program_counter_index)=run_create_group group_code_index int 0 clone_index program_counter_index index_group_index index_group program_counter in run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) new_program_counter_index (index_group_index+int) survived_main_index_group newborn_main_index_group main_index_group new_index_group new_program_counter (DIM.insert (int_index+clone_index) index_group_index variable) engine widget
    Linear_clone {int_index,clone_number,int}->let new_code_index=this_code_index+1 in let (new_program_counter,new_newborn_main_index_group,new_program_counter_index)=run_clone int clone_number (clone_index+clone_number) new_code_index program_counter_index newborn_main_index_group program_counter in run_coroutine_a linear_coroutine main_index clone_index new_code_index new_program_counter_index index_group_index survived_main_index_group new_newborn_main_index_group main_index_group index_group new_program_counter (DIM.insert (int_index+clone_index) int variable) engine widget
    Linear_wake_group {int_index,dynamic_int,int}->let new_int=dynamic_int.dynamic_int engine widget in if int<=new_int then error "run_coroutine_a: error 1" else let new_index_group_index=intmap_lookup (int_index+clone_index) variable+new_int in let (new_index_group_map,maybe_single_index_group)=intmap_delete_maybe_lookup new_index_group_index index_group in case maybe_single_index_group of
        Nothing->run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget
        Just single_index_group->let (new_widget,new_engine,new_variable,new_program_counter,new_index_group,new_survived_main_index_group,new_new_index_group_index,new_program_counter_index)=run_coroutine linear_coroutine program_counter_index index_group_index DS.empty DS.empty single_index_group new_index_group_map program_counter variable engine widget in run_coroutine_a linear_coroutine main_index clone_index (this_code_index+1) new_program_counter_index new_new_index_group_index survived_main_index_group newborn_main_index_group main_index_group (if DS.null new_survived_main_index_group then new_index_group else DIM.insert new_index_group_index new_survived_main_index_group new_index_group) new_program_counter new_variable new_engine new_widget
    Linear_dynamic_clone {int_index,code_index,clone_number,dynamic_int,int}->let new_int=dynamic_int.dynamic_int engine widget-1 in if new_int<0 then run_coroutine_a linear_coroutine main_index clone_index code_index program_counter_index index_group_index survived_main_index_group newborn_main_index_group main_index_group index_group program_counter variable engine widget else if int<new_int then error "run_coroutine_a: error 2" else let new_code_index=this_code_index+1 in let (new_program_counter,new_newborn_main_index_group,new_program_counter_index)=run_clone new_int clone_number (clone_index+clone_number) new_code_index program_counter_index newborn_main_index_group program_counter in run_coroutine_a linear_coroutine main_index clone_index new_code_index new_program_counter_index index_group_index survived_main_index_group new_newborn_main_index_group main_index_group index_group new_program_counter (DIM.insert (int_index+clone_index) new_int variable) engine widget

run_kill_group::Int->Int->Int->DIM.IntMap (DS.Seq Int)->DIM.IntMap Program_counter->(DIM.IntMap Program_counter,DIM.IntMap (DS.Seq Int))
run_kill_group int index index_group_index index_group program_counter=if int<=index then (program_counter,index_group) else let (new_index_group,maybe_single_index_group)=intmap_delete_maybe_lookup (index_group_index+index) index_group in case maybe_single_index_group of
    Nothing->run_kill_group int (index+1) index_group_index new_index_group program_counter
    Just single_index_group->run_kill_group int (index+1) index_group_index new_index_group (DF.foldl' (flip DIM.delete) program_counter single_index_group)

run_create_group::DIM.IntMap Int->Int->Int->Int->Int->Int->DIM.IntMap (DS.Seq Int)->DIM.IntMap Program_counter->(DIM.IntMap Program_counter,DIM.IntMap (DS.Seq Int),Int)
run_create_group group_code_index int index clone_index program_counter_index index_group_index index_group program_counter=if int<=index then (program_counter,index_group,program_counter_index) else run_create_group group_code_index int (index+1) clone_index (program_counter_index+1) index_group_index (intmap_insert (index_group_index+index) (DS.singleton program_counter_index) index_group) (intmap_insert program_counter_index (Program_counter {code_index=intmap_lookup index group_code_index,clone_index=clone_index}) program_counter)

run_clone::Int->Int->Int->Int->Int->DS.Seq Int->DIM.IntMap Program_counter->(DIM.IntMap Program_counter,DS.Seq Int,Int)
run_clone int clone_number clone_index code_index program_counter_index main_index_group program_counter=if int<1 then (program_counter,main_index_group,program_counter_index) else run_clone (int-1) clone_number (clone_index+clone_number) code_index (program_counter_index+1) (main_index_group DS.|> program_counter_index) (intmap_insert program_counter_index (Program_counter {code_index=code_index,clone_index=clone_index}) program_counter)