{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE NamedFieldPuns #-}

module Engine.Coroutine where

import Engine.Type
import qualified Data.IntMap as DIM

from_coroutine::Coroutine a->(DIM.IntMap (Linear_coroutine a),Int,Int)
from_coroutine coroutine=let (linear_coroutine,coroutine_index,int_index,code_index)=from_coroutine_a coroutine 0 0 1 DIM.empty in (DIM.insert code_index Linear_end linear_coroutine,coroutine_index,int_index)

from_coroutine_a::Coroutine a->Int->Int->Int->DIM.IntMap (Linear_coroutine a)->(DIM.IntMap (Linear_coroutine a),Int,Int,Int)
from_coroutine_a this_coroutine code_index int_index coroutine_index linear_coroutine=case this_coroutine of
    Done->(linear_coroutine,coroutine_index,int_index,code_index)
    Emit {emit}->(DIM.insert code_index (Linear_emit {emit=emit}) linear_coroutine,coroutine_index,int_index,code_index+1)
    Wait {dynamic_int}->(DIM.insert (code_index+1) (Linear_wait {int_index=int_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) linear_coroutine),coroutine_index,int_index+1,code_index+2)
    Forever {coroutine}->let (new_linear_coroutine,new_coroutine_index,new_int_index,new_code_index)=from_coroutine_a coroutine code_index int_index coroutine_index linear_coroutine in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) new_linear_coroutine,new_coroutine_index,new_int_index,new_code_index+1)
    While {dynamic_bool,coroutine}->let (new_linear_coroutine,new_coroutine_index,new_int_index,new_code_index)=from_coroutine_a coroutine (code_index+1) int_index coroutine_index linear_coroutine in (DIM.insert new_code_index (Linear_jump {code_index=code_index}) (DIM.insert code_index (Linear_false_jump {code_index=new_code_index+1,dynamic_bool=dynamic_bool}) new_linear_coroutine),new_coroutine_index,new_int_index,new_code_index+1)
    Repeat {dynamic_int,coroutine}->let (new_linear_coroutine,new_coroutine_index,new_int_index,new_code_index)=from_coroutine_a coroutine (code_index+2) (int_index+1) coroutine_index linear_coroutine in let new_new_code_index=new_code_index+1 in (DIM.insert new_code_index (Linear_one_more_jump {code_index=code_index+1,int_index=int_index}) (DIM.insert (code_index+1) (Linear_one_less_jump {code_index=new_new_code_index,int_index=int_index}) (DIM.insert code_index (Linear_dynamic_int {int_index=int_index,dynamic_int=dynamic_int}) new_linear_coroutine)),new_coroutine_index,new_int_index,new_new_code_index)
    Then {first_coroutine,second_coroutine}->let (first_linear_coroutine,first_coroutine_index,first_int_index,first_code_index)=from_coroutine_a first_coroutine code_index int_index coroutine_index linear_coroutine in let (second_linear_coroutine,second_coroutine_index,second_int_index,second_code_index)=from_coroutine_a second_coroutine first_code_index int_index coroutine_index first_linear_coroutine in (second_linear_coroutine,max first_coroutine_index second_coroutine_index,max first_int_index second_int_index,second_code_index)
    Fork {first_coroutine,second_coroutine}->let (first_linear_coroutine,first_coroutine_index,first_int_index,first_code_index)=from_coroutine_a first_coroutine (code_index+2) (int_index+2) (coroutine_index+1) linear_coroutine in let (second_linear_coroutine,second_coroutine_index,second_int_index,second_code_index)=from_coroutine_a second_coroutine (first_code_index+1) first_int_index first_coroutine_index first_linear_coroutine in let new_int_index=int_index+1 in (DIM.insert second_code_index (Linear_deregister {first_int_index=int_index,second_int_index=new_int_index}) (DIM.insert first_code_index (Linear_jump {code_index=second_code_index}) (DIM.insert (code_index+1) (Linear_fork {code_index=first_code_index+1,coroutine_index=coroutine_index}) (DIM.insert code_index (Linear_register {first_int_index=int_index,second_int_index=new_int_index,int=2}) second_linear_coroutine))),second_coroutine_index,second_int_index,second_code_index+1)
    If {dynamic_bool,first_coroutine,second_coroutine}->let (first_linear_coroutine,first_coroutine_index,first_int_index,first_code_index)=from_coroutine_a first_coroutine (code_index+1) int_index coroutine_index linear_coroutine in let (second_linear_coroutine,second_coroutine_index,second_int_index,second_code_index)=from_coroutine_a second_coroutine (first_code_index+1) int_index coroutine_index first_linear_coroutine in (DIM.insert first_code_index (Linear_jump {code_index=second_code_index}) (DIM.insert code_index (Linear_false_jump {code_index=first_code_index+1,dynamic_bool=dynamic_bool}) second_linear_coroutine),max first_coroutine_index second_coroutine_index,max first_int_index second_int_index,second_code_index)